### ISSUE TITLE
Líneas largas de código

### ISSUE THREAD

**Issue by humitos** [PyAr/tutorial-en-papel#10]
Actualmente las líneas largas que contienen código se caen a la siguiente línea con una flecha:

![Screenshot_2022-11-01_11-45-38](https://user-images.githubusercontent.com/244656/199216419-be52a219-7084-4d38-af38-5daa3057ea64.png)

¿Está bien esto? ¿Queremos hacer algún cambio acá?

**Comment by cacrespo** [comment]
De mi lado estoy OK con eso de marcar los saltos de linea. Por otro lado, no se me ocurre qué otra cosa podríamos hacer.

**Comment by humitos** [comment]
Perfecto! Yo creo que está bien así también. Cierro el issue entonces.
