### ISSUE TITLE
Caracteres de lenguajes asiáticos

### ISSUE THREAD

**Issue by humitos** [PyAr/tutorial-en-papel#15]
```
Missing character: There is no 景 (U+666F) in font Fira Code Regular/OT:script=l
atn;language=dflt;!
Missing character: There is no 太 (U+592A) in font Fira Code Regular/OT:script=l
atn;language=dflt;!
Missing character: There is no 郎 (U+90CE) in font Fira Code Regular/OT:script=l
atn;language=dflt;!
```

Aparecen en https://github.com/python/cpython/blob/b3cafb60afeb2300002af9982d43703435b8302d/Doc/tutorial/controlflow.rst?plain=1#L76-L77

y se renderizan mal:

![Screenshot_2022-11-01_19-07-22](https://user-images.githubusercontent.com/244656/199306441-446a5f0a-5873-4a8a-a735-c67182ce6090.png)

No estoy seguro si tenemos muchas posibilidades de arreglarlos 😞

**Comment by cacrespo** [comment]
¿No habrá manera de decirle a Sphinx que utilice la fuente Fira Code y si no está disponible el caracter utilice otra por defecto que si lo tenga?

**Comment by humitos** [comment]
Si se puede, no sé cómo hacerlo 😄 

Cuando trabajé con caracteres asiáticos, escribí esta guía https://docs.readthedocs.io/en/stable/guides/pdf-non-ascii-languages.html#sphinx-pdfs-with-unicode --pero la no sé si es lo mejor seguirla siendo que nuestro PDF **solo** tiene esos 3 caracteres y nada más.

Lo más simple de todo es reemplazar esos tres caracteres por otro nombre. Incluso, estaba pensando que podíamos usar un nombre en español que tenga `ñ`, como _Iñaki_, 😉 . Al final, este es el único lugar en dónde se hace uso de esto, así que no modifica el texto en los siguientes párrafos.

**Comment by cacrespo** [comment]
> Lo más simple de todo es reemplazar esos tres caracteres por otro nombre. Incluso, estaba pensando que podíamos usar un nombre en español que tenga ñ, como Iñaki, wink . Al final, este es el único lugar en dónde se hace uso de esto, así que no modifica el texto en los siguientes párrafos.

+1000 a reemplazar la palabra entera (o palabras... vaya uno a saber) por Iñaki.
