### ISSUE TITLE
Revisar títulos

### ISSUE THREAD

**Issue by humitos** [PyAr/tutorial-en-papel#23]
Los títulos usan "title case" porque es una regla de estilo en inglés. Sin embargo, en castellano, lo correcto es que solo la primera esté en mayúscula.

![Screenshot_2022-11-05_21-55-55](https://user-images.githubusercontent.com/244656/200141044-0e6b282a-dd87-4c42-bb8f-d69691eb90aa.png)

Además, en este caso en particular, el título correcto podría ser "Crear entornos virtuales", en vez de "Creando...". Hay otro capítulos y secciones que tienen el mismo problema.

**Comment by cacrespo** [comment]
Para este puntual y todos los similares que encuentre, levanto el issue en [python-docs-es](https://github.com/python/python-docs-es)

**Comment by humitos** [comment]
Si estamos de acuerdo en que tienen que ser todo en minúscula y con el verbo en infinitivo, será menos trabajo directamente abrir el PR, supongo. Sino, podemos conversarlo primero y luego hacemos las PRs.

**Comment by cacrespo** [comment]
Estoy de acuerdo con escribir todo en minúscula y demás. De hecho, alguna vez mencionamos este mismo tema en el canal de Telegram y el acuerdo general fue pasar a minúsculas el título.

[Acá](https://github.com/python/python-docs-es/issues/2173) abrí el issue y voy a ir levantando todos los casos similares. Si nadie lo toma pronto lo agarro yo.

**Comment by humitos** [comment]
¿Te parece bien también cambiar los verbos de gerundio a infinitivo? Ejemplo, cambiar "Creando" por "Crear".

**Comment by cacrespo** [comment]
> ¿Te parece bien también cambiar los verbos de gerundio a infinitivo? Ejemplo, cambiar "Creando" por "Crear".

Yep.

**Comment by humitos** [comment]
Sí. Tiene sentido. Quizás haya otros títulos y subtítulos que no quede bien está regla, pero "la base está" 🙂

**Comment by cacrespo** [comment]
Cierro este issue porque reviso esto mismo en #25
