### ISSUE TITLE
Ajuste ad-hoc página 1

### ISSUE THREAD

**Issue by cacrespo** [PyAr/tutorial-en-papel#24]
Voy contra todas las reglas universales de la automatización... pero no me gusta ni un poco el texto de presentación que está en la página 1. De hecho, al quitar el glosario la frase con la que se cierra el material no tiene sentido.
Marco en rojo lo que excluiría.

![image](https://user-images.githubusercontent.com/10950697/200669233-75b18d7e-26ed-4a50-b57c-5872bf1759c1.png)

**Comment by humitos** [comment]
> Marco en rojo lo que excluiría.

Perfecto, esto se puede quitar sin problema.

> Voy contra todas las reglas universales de la automatización...

No te metas con la automatización que hay bardo 😝
